### ISSUE TITLE
SIRF build with gnu 4.8.5

### ISSUE THREAD

**Issue by gfardell** [SyneRBI/SIRF#774]
Using gnu 4.8.5 I have a couple of build errors:

```
`src/Registration/NiftyMoMo/BSplineTransformation.cpp: In member function ‘void NiftyMoMo::BSplineTransformation::CPGToDVF3D(nifti_image*)’:

src/Registration/NiftyMoMo/BSplineTransformation.cpp:532:76: error: ‘NiftyMoMo::BSplineTransformation::controlPointGridImage’ is not a variable in clause ‘share ’
  firstZCPG, firstYCPG, firstXCPG, indCPG, indDVF, indTmp, valX, valY, valZ)
```
This is fixed by removing controlPointGridImage from the OpenMP shared declaration in CPGToDVF2D and CPGToDVF3D which shouldn't change any functionality as anything declared before ```#pragma openmp parallel``` will be shared default.

src/common/include/sirf/common/ANumRef.h
'invalid_argument’ is not a member of ‘std’

This is fixed by including the stdexcept header

**Comment by rijobro** [comment]
hi Gemma, 
Great that you've managed to find a fix. Would you mind creating a PR and we can see if the changes are OK with Travis?

**Comment by gfardell** [comment]
I have, but I can't push my branch. I assume I need repository permissions?

**Comment by rijobro** [comment]
Simplest would be to create a fork, push to there and then create a PR to master from there. you can obviously delete your fork once the PR is merged if you'd like.
