### ISSUE TITLE
Nose is unmaintained and no longer works with Python 3.10

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#1148]
Errors
```
  File "/home/kthielem/.local/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
```
This won't be fixed https://github.com/nose-devs/nose/issues/1099

That issue mentions some solutions
- move to `nose2`
- move to `pytest` (used by STIR by the way)
- ```
   $ pip uninstall -y nose
   $ pip install -U nose --no-binary :al
  ```
- ```
   $ pip uninstall -y nose
   $ pip install nose-py3
   ```
I've tried the latter (on CentOS) and it worked.

I don't know if `nose-py3` is maintained and good to use long-term.

@casperdcl any suggestions?

**Comment by KrisThielemans** [comment]
I've looked into transitioning to `pytest`. It shouldn't be too much work as `pytest` has tried to be accommodate `nose` users.
Test discovery rules are a bit different though, so `pytest` doesn't find all our tests (essentially because files are called `tests_*` and not `test_*`), see https://docs.pytest.org/en/6.2.x/goodpractices.html#conventions-for-python-test-discovery

This might work:
- add `pytest` to `requirements.txt` and remove `nose` (both in SIRF and SIRF-SuperBuild unfortunately)
- add `[pytest.ini]` in .../pSTIR/tests and ../pGadgetron/tests that says
  ```
  [pytest]
  python_files = test*.py
  ```
- adjust `CMakeLists.txt` to use `pytest` (will likely need to change the `exclude_files` variable to say `--ignore=...`

Check that the same tests are being picked up, e.g.
````
python3 -m nose --ignore=test_algebra.py  --collect-only -v
python3 -m pytest --ignore=test_algebra.py  --collect-only
```

However, ideally get rid of the exclusion stuff and handle everything via `pytest` (as it should handle `unittest` as well), such that we can simply do `pytest` in the directory, as people will expect.

Ideally we'd also address the multiple warnings we're getting with `pytest` like this
```
  /home/sirfuser/.local/lib/python3.10/site-packages/_pytest/python.py:199: PytestReturnNotNoneWarning: Expected None, but tests_two.py::test_main returned (0, 62), which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
```
This is because the tests contain a function `test_main` that returns the number of failed and the number of total tests, to be called by [runner](https://github.com/SyneRBI/SIRF/blob/80ccacad280c87c8506df3ca101d7fa8d2c9c3d8/src/common/Utilities.py#L411). I guess the simplest strategy would be to
1. rename `test_main` to something that isn't picked up by `pytest`  (or excluded it)
2. add another function `test_func_for_pytest` that calls `test_main` and raises an `AssertionError` if `failed>0`

**Comment by casperdcl** [comment]
Is `test_main` even required? `pytest` has such functionality built-in.

**Comment by KrisThielemans** [comment]
I think  @evgueni-ovtchinnikov  needs something like this for recording "true" values. (We want to get rid of that in most cases, but in some it is unavoidable, as there's no way to compute them on first principles).

**Comment by mdmintz** [comment]
If people still need to use ``nose``, it's been patched for newer versions of Python in ``pynose``:
https://pypi.org/project/pynose/

``pip install pynose``, then you can run tests with ``pynose`` or ``nosetests``.

Changes in ``pynose`` from legacy ``nose`` include:
* Fixes "AttributeError: module 'collections' has no attribute 'Callable'."
* Fixes "AttributeError: module 'inspect' has no attribute 'getargspec'."
* Fixes "ImportError: cannot import name '_TextTestResult' from 'unittest'."
* Fixes "RuntimeWarning: TestResult has no addDuration method."
* Fixes all ``flake8`` issues from the original ``nose``.
* Replaces the ``imp`` module with the newer ``importlib`` module.
* The default logging level now hides "debug" logs for less noise.
* The ``-s`` option is always active to see the output of ``print()``.
* Adds ``--co`` as a shortcut to using ``--collect-only``.
