### ISSUE TITLE
MATLAB and HDF5 on Windows

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#382]
On Windows MATLAB does not work with HDF5 versions we require (1.8.17 or later). Its `H5.get_libversion()` function claims that MATLAB uses 1.8.12, however the HDF5 dll's in MATLAB's `bin` are clearly different from those in HDF5 1.8.12 (they are of different size and MATLAB's are more recent). 
The good news is: MATLAB's HDF5 dlls do not conflict with 1.8.12, and the bad news is: Python scripts crash if SIRF is build with 1.8.12. Luckily, they work with MATLAB's dlls.
Hence a trick to make both MATLAB and Python happy is to put MATLAB's subfolder `bin\win64` before HDF5's subfolder `bin` in Windows' path, so that MATLAB's dlls are loaded.

**Comment by KrisThielemans** [comment]
I tried to use static libraries for HDF5, which I thought would remove causes for conflicts. I did that by adding ` -DHDF5_USE_STATIC_LIBRARIES=ON` to `External_ISMRMRD.cmake` and `External_SIRF.cmake`. However, that leads to linking problems like
```
1>libhdf5.lib(H5T.c.obj) : error LNK2001: unresolved external symbol _forceCRTManifestCUR
1>libhdf5.lib(H5HFdblock.c.obj) : error LNK2019: unresolved external symbol __imp___iob_func referenced in function H5HF_man_dblock_destroy
1>libhdf5.lib(H5Cdbg.c.obj) : error LNK2001: unresolved external symbol __imp___iob_func
1>OLDNAMES.lib(timezone.obi) : error LNK2001: unresolved external symbol __imp_timezone
1>libhdf5.lib(H5system.c.obj) : error LNK2019: unresolved external symbol __imp__vscprintf referenced in function c99_vsnprintf
```
Reason is that ISMRMRD library etc are compiled with `/MD` but the HDF5 library isn't. Apparently you cannot mix them. oh well.

**Comment by KrisThielemans** [comment]
A potential reason for the different DLL files is that Matlab compiled their own, e.g. with a different compiler.

I checked on https://support.hdfgroup.org/HDF5/release/cmakebuild518.html. They don't supply a version for "recent" Visual Studio (I have 2015, aka VS14), so I cannot download it.

I managed to get MATLAB SIRF to work with HDF5 5.1.18 compiled myself. However, this version does not support Visual Studio 2015 or later... I get into 2 problems:
- compilation problem related to the global variable `timezone` no longer existing. Fix is discussed in various places (e.g. [here](https://gitlab.kitware.com/vtk/vtk/merge_requests/446/diffs#3cd0abd201feea1684c855281472b509ef5bb98e)).
We need to patch HDF5's `config/cmake/ConfigureChecks.cmake`
   ```
  set (H5_HAVE_TIMEZONE 1) 
   ```
   this needs to be set to 0.

- their CMakeLists.txt has problems when building with `RelWithDebInfo`, see same as [here](https://phabricator.mitk.org/T24555). It can be patched for that as well. Or we just say to build with `Release` only of course.

I then need some mods to the SIRF-SuperBuild to use this version of course. Finally, i needed to make sure that the dir where the hdf5.lib was installed (i.e. `SuperBuild/INSTALL`) was in the path before any other locations where I have hdf5 stuff, so I put it first.

But with all this: success!

**Comment by KrisThielemans** [comment]
success = all MATLAB tests succeeded. However, all Python tests failed. Presumably because of version conflicts between anaconda's (more recent) hdf5 and the one I compiled.

**Comment by KrisThielemans** [comment]
I believe the HDF5 compilation problems on Windows were resolved with https://github.com/CCPPETMR/SIRF-SuperBuild/pull/251. Current status therefore:
- still can only build with `Release`
- HDF5 version when using MATLAB on Windows is currently hard-wired (should use `H5.get_libversion()`)
- still conflict with Python libs, so you  have to build 2 separate versions (one with Matlab and one without) https://github.com/CCPPETMR/SIRF-SuperBuild/pull/252

This problem might also apply on Linux-type systems. Can anyone confirm if SIRF MATLAB on Linux works? (MR tests should throw errors)

**Comment by KrisThielemans** [comment]
outdated, and we don't support MATLAB anymore
