### ISSUE TITLE
compilation problem with recent STIR

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF#639]
while testing https://github.com/SyneRBI/SIRF-SuperBuild/pull/377, all Travis jobs fails, e.g. https://travis-ci.org/github/SyneRBI/SIRF-SuperBuild/jobs/679504203#L22496
```
‘void sirf::ListmodeToSinograms::compute_fan_sums_(bool)’:
/home/travis/build/SyneRBI/SIRF-SuperBuild/sources/SIRF/src/xSTIR/cSTIR/stir_x.cpp:67:38: error: conversion from ‘std::shared_ptr<stir::ListRecord>’ to non-scalar type ‘std::shared_ptr<stir::CListRecord>’ requested
    lm_data_ptr->get_empty_record_sptr();
```
Current STIR (i.e. 4.0.0) needs `shared_ptr<ListRecord>`, but this is sadly incompatible with 4.0.0alpha. (seems we created a mess).

I don't understand why this hasn't shown up in `DEVEL_BUILD=ON` cases though

**Comment by KrisThielemans** [comment]
we could potentially check the preprocessor symbol  `STIR_VERSION_STRING`, set to `"4.0.0-alpha"` or "4.0.0", see
https://github.com/UCL/STIR/blob/063cf26d4a884b8906ac8f91c9ba66e17b6b5431/CMakeLists.txt#L51-L53 and https://github.com/UCL/STIR/blob/8fb1e90ed7cd61b8570ad5287587ccc9d4bd6cd6/src/cmake/STIRConfig.h.in#L37

However, it doesn't seem possible to compare strings with the preprocessor (or at least not without [jumping through a lot of hoops](https://stackoverflow.com/questions/2335888/how-to-compare-strings-in-c-conditional-preprocessor-directives)

**Comment by KrisThielemans** [comment]
This problem was already solved in #574. Indeed, it is only the non-Devel-build job that were failing. sorry.

The problem is that SIRF 2.1 doesn't work with (final) STIR 4.0.0, not a surprise. So, we need to bump the SIRF version as well in this PR
